import Head from "next/head";

import Hero from "~/components/hero";
import Navbar from "~/components/navbar";
import Layout from "~/layout";
import { getStaticProps } from "~/utils";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <Navbar />
                <Hero />
            </Layout>
        </>
    );
}

export { getStaticProps };